name: run docker image build on artifact

on: 
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string 
      service_name:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
        
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          
      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
    
      - run: ls path/to/artifact/
