name: run docker image build on artifact

on: 
  workflow_call:
    inputs:
      is_tag:
        required: true
        type: boolean
      build_image:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
        
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          
      - name: get artifacts frome previous job
        uses: actions/download-artifact@v4
        with:
          name: $VERSION.tar.gz
          path: path/to/artifact
    
      - name: cheact artifacts available
        run: ls path/to/artifact/
      
      - name: set environmentals
        run: |
          echo "VERSION=`jq -r '.version' package.json`" >> $GITHUB_ENV
          echo "PULL_TAG=pull-${{ github.event.number }}" >> $GITHUB_ENV
      
      - name: set docker tag
        run: echo "GIT_TAG=`echo $(git tag --sort=committerdate | tail -1)`" >> $GITHUB_ENV
        
      - name: check version is set correctly
        run: |
          set -e 
          echo $VERSION
          
      - name: unpackage artifact from previous run
        if: ${{ inputs.is_tag == false }}
        run: |
          set -e
          tar -xzvf path/to/artifact/$VERSION.tar.gz
          
      - name: unpackage artifact from previous run
        if: ${{ inputs.is_tag == true }}
        run: |
          set -e
          tar -xzvf path/to/artifact/$GIT_TAG.tar.gz
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}       
          
      - name: build docker file
        run: |
          set -e
          docker build --build-arg otrl_service_name=${{ inputs.build_image }} --build-arg version=${version} -t ${{ inputs.build_image }} .
          
      - name: tag docker file
        if: ${{ inputs.is_tag == false }}
        run: |
          set -e
          docker tag ${{ inputs.build_image }} otrl/${{ inputs.build_image }}:$PULL_TAG
          
      - name: push docker image
        if: ${{ inputs.is_tag == false }}
        run: |
          set -e
          docker push otrl/${{ inputs.build_image }}:$PULL_TAG
          
      - name: tag docker file
        if: ${{ inputs.is_tag == true }}
        run: |
          set -e
          docker tag ${{ inputs.build_image }} otrl/${{ inputs.build_image }}:$GIT_TAG
          
      - name: push docker image
        if: ${{ inputs.is_tag == true }}
        run: |
          set -e
          docker push otrl/${{ inputs.build_image }}:$GIT_TAG         
          
          
          
