name: test

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  id-token: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

on:
  pull_request:
    branches:
      - master
      - /^[0-9]+\.[0-9]+\.[0-9]+(\-[0-9]+)?$/
      - /^feature\/.+$/
  push:
    tags:
      - '*'
  
jobs:
  doing-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and test
        run: echo "i did stuff"
